/*
 * This source file was generated by the Gradle 'init' task
 */
package rpg;
import java.util.Scanner;

public class App {
    public Player escolherPlayer(Scanner sc, Dados dados) {
        System.out.println("|__________________________________|");
        System.out.println("|------------- CLASSES ------------|");
        System.out.println("| 1 - Barbaro                      |");
        System.out.println("| 2 - Ladino                       |");
        System.out.println("| 3 - Hunter                       |");
        System.out.println("|--------------      --------------|");
        System.out.println("| System: Qual desejas?            |");
        int escolhaClasse = sc.nextInt();
        sc.nextLine(); // Consome o restante da linha após o número.

        System.out.println("\n| System: Qual o seu nome?         |");
        String nomePlayer = sc.nextLine();

        System.out.println("\n| System: Rolem os dados!          |");
        dados.rolarDados();

        Player player;
        if (escolhaClasse == 1) {
            player = new Barbaro(nomePlayer, dados.rolarESomar(), dados.rolarESomar(), dados.rolarESomar());
            System.out.println("\n| System: Seu bárbaro foi criado com os seguintes atributos: ");
        } else if (escolhaClasse == 2) {
            player = new Ladino(nomePlayer, dados.rolarESomar(), dados.rolarESomar(), dados.rolarESomar());
            System.out.println("\n| System: Seu ladino foi criado com os seguintes atributos: ");
        } else {
            player = new Hunter(nomePlayer, dados.rolarESomar(), dados.rolarESomar(), dados.rolarESomar());
            System.out.println("\n| System: Seu hunter foi criado com os seguintes atributos: ");
        }

        System.out.println(player.toString() + "\n\n\n\n");
        
        return player;
    }

    public static void main(String[] args) {
        App app = new App();
        Scanner sc = new Scanner(System.in);
        Dados dados = new Dados();

        //Para Escolher o jogador
        Player player = app.escolherPlayer(sc, dados);
        Scene vila = new Villa(player);
        
        System.out.print("Aperte Enter para comecar o jogo!\n\n\n\n");
        sc.nextLine();
        
        //Começa a primeira fase
        vila.exibirCena();
        vila.exibirChoises();
        int choise = sc.nextInt();
        sc.nextLine();
        System.out.println("");
        vila.processChoise(choise);
       
        // Fechar scanner
        sc.close();
    }
}